devices:

  # ISP1 DEVICES

  - device_type: cisco_ios
    host: 10.0.0.1
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 10.0.0.2
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 10.0.0.3
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 10.0.0.4
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 10.0.0.5
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 10.0.0.6
    username: Samuel
    password: Samuel@123
    port: 22

  # ISP2 DEVICES

  - device_type: cisco_ios
    host: 10.0.1.1
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 10.0.1.2
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 10.0.1.11
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 10.0.1.12
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 10.0.1.21
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 10.0.1.22
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 10.0.1.101
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 10.0.1.102
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 10.0.1.201
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 10.0.1.202
    username: Samuel
    password: Samuel@123
    port: 22

  # SITES DEVICES

  - device_type: cisco_ios
    host: 20.0.0.8
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 20.0.0.9
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 20.0.0.10
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 20.0.0.16
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 20.0.0.18
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: mikrotik_routeros
    host: 20.0.0.19
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: juniper_junos
    host: 20.0.0.20
    username: root
    password: Samuel@123
    port: 22

  # DC1 DEVICES

  - device_type: cisco_ios
    host: 30.0.0.1
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 30.0.0.2
    username: Samuel
    password: Samuel@123
    port: 22

  # DC2 DEVICES

  - device_type: huawei_vrp
    host: 30.0.1.2
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: huawei_vrp
    host: 30.0.1.3
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: huawei_vrp
    host: 30.0.1.4
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: huawei_vrp
    host: 30.0.1.5
    username: Samuel
    password: Samuel@123
    port: 22

  # HQ1 DEVICES

  - device_type: cisco_ios
    host: 20.0.0.1
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 20.0.0.2
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 20.0.0.5
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 20.0.0.6
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: huawei_vrp
    host: 20.0.0.17
    username: Samuel
    password: Samuel@123
    port: 22

  # HQ2 DEVICES

  - device_type: huawei_vrp
    host: 30.0.2.3
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: huawei_vrp
    host: 30.0.2.4
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 30.0.2.5
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 30.0.2.10
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 30.0.2.13
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 30.0.2.14
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 30.0.2.17
    username: Samuel
    password: Samuel@123
    port: 22
