devices:
  - device_type: cisco_ios
    host: 10.0.0.1
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 10.0.0.2
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 10.0.1.1
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: cisco_ios
    host: 10.0.1.2
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: huawei_vrp
    host: 30.0.1.2
    username: Samuel
    password: Samuel@123
    port: 22

  - device_type: juniper_junos
    host: 20.0.0.20
    username: root
    password: Samuel@123
    port: 22

  - device_type: mikrotik_routeros
    host: 20.0.0.19
    username: Samuel
    password: Samuel@123
    port: 22
