- name: Display Running Configuration on Network Devices
  hosts: cisco_ios,huawei_vrp
  gather_facts: false

  tasks:

    - name: Show Huawei config
      community.network.ce_command:
        commands:
          - display current-configuration
      register: ce_output
      when: ansible_network_os == 'community.network.ce'

    - name: Show Cisco config
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: ios_output
      when: ansible_network_os == 'cisco.ios.ios'

    - name: Print Huawei config
      ansible.builtin.debug:
        var: ce_output.stdout_lines
      when: ce_output is defined

    - name: Print Cisco config
      ansible.builtin.debug:
        var: ios_output.stdout_lines
      when: ios_output is defined
